# Generated by Django 5.2.6 on 2026-06-16 10:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('name',), 'verbose_name': 'Переговорная', 'verbose_name_plural': 'Переговорные'},
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Room', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='qr_code_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Доступна'), ('maintenance', 'На обслуживании'), ('unavailable', 'Недоступна')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
