# Generated by Django 5.2.6 on 2026-06-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_room_options_room_created_at_room_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="rooms/"),
        ),
    ]
