# Generated by Django on 2026-06-18
from django.db import migrations
import uuid


def add_sample_rooms(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    
    sample_rooms = [
        {
            'name': 'Переговорная "Альфа"',
            'description': 'Уютная переговорная для небольших встреч и обсуждений. Оснащена проектором и доской.',
            'capacity': 8,
            'location': '3 этаж, офис 301',
            'status': 'available',
        },
        {
            'name': 'Переговорная "Бета"',
            'description': 'Современная переговорная для командных встреч. Видеоконференц-связь, флипчарт.',
            'capacity': 12,
            'location': '3 этаж, офис 302',
            'status': 'available',
        },
        {
            'name': 'Конференц-зал "Гамма"',
            'description': 'Большой конференц-зал для презентаций и крупных совещаний. Проектор, микрофоны, система видеоконференц-связи.',
            'capacity': 25,
            'location': '4 этаж, зал 401',
            'status': 'available',
        },
        {
            'name': 'Переговорная "Дельта"',
            'description': 'Компактная комната для интервью и личных встреч. Тихая и уединённая.',
            'capacity': 4,
            'location': '2 этаж, офис 205',
            'status': 'available',
        },
        {
            'name': 'Переговорная "Омега"',
            'description': 'Технически оснащённая комната для онлайн-встреч. Два монитора, профессиональная камера, звукоизоляция.',
            'capacity': 6,
            'location': '3 этаж, офис 303',
            'status': 'available',
        },
    ]
    
    for room_data in sample_rooms:
        Room.objects.create(
            name=room_data['name'],
            description=room_data['description'],
            capacity=room_data['capacity'],
            location=room_data['location'],
            status=room_data['status'],
            qr_code_id=str(uuid.uuid4()),
        )


def remove_sample_rooms(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    room_names = [
        'Переговорная "Альфа"',
        'Переговорная "Бета"',
        'Конференц-зал "Гамма"',
        'Переговорная "Дельта"',
        'Переговорная "Омега"',
    ]
    Room.objects.filter(name__in=room_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_options_room_created_at_room_description_and_more'),
    ]

    operations = [
        migrations.RunPython(add_sample_rooms, remove_sample_rooms),
    ]