# Generated by Django 5.2.6 on 2026-06-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_add_sample_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Фотография переговорной комнаты', null=True, upload_to='rooms/'),
        ),
    ]
