# Generated by Django 5.2.6 on 2026-06-16 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_alter_room_options_room_created_at_room_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAccessPolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('view', 'Только просмотр'), ('book', 'Бронирование'), ('manage', 'Управление')], default='book', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_policies', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_access_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Политика доступа',
                'verbose_name_plural': 'Политики доступа',
                'ordering': ('room', 'user'),
                'unique_together': {('room', 'user')},
            },
        ),
    ]
