# Generated by Django 6.0.6 on 2026-06-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAccessPolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('view', 'Только просмотр'), ('book', 'Бронирование'), ('manage', 'Управление')], default='book', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_policies', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Политика доступа',
                'verbose_name_plural': 'Политики доступа',
                'ordering': ('room', 'user'),
            },
        ),
    ]
