# Generated by Django on 2026-06-18
from django.db import migrations


def add_default_access_policies(apps, schema_editor):
    RoomAccessPolicy = apps.get_model('access_control', 'RoomAccessPolicy')
    Room = apps.get_model('rooms', 'Room')
    User = apps.get_model('users', 'User')
    
    # Get all users and all rooms
    users = User.objects.all()
    rooms = Room.objects.all()
    
    # Create access policy for each user-room combination
    policies_created = 0
    for user in users:
        for room in rooms:
            policy, created = RoomAccessPolicy.objects.get_or_create(
                user=user,
                room=room,
                defaults={
                    'access_level': 'book',
                    'is_active': True,
                }
            )
            if created:
                policies_created += 1
    
    print(f"Created {policies_created} access policies")


def remove_default_access_policies(apps, schema_editor):
    RoomAccessPolicy = apps.get_model('access_control', 'RoomAccessPolicy')
    # Remove all policies (be careful in production!)
    count, _ = RoomAccessPolicy.objects.all().delete()
    print(f"Removed {count} access policies")


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        ('rooms', '0003_add_sample_rooms'),
    ]

    operations = [
        migrations.RunPython(add_default_access_policies, remove_default_access_policies),
    ]