# Generated by Django 5.2.6 on 2026-06-16 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_alter_room_options_room_created_at_room_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтверждена'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=500)),
                ('participants_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ('-start_time',),
                'unique_together': {('room', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='RoomEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_authorized', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='bookings.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rooms.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вход в комнату',
                'verbose_name_plural': 'Входы в комнаты',
                'ordering': ('-entry_time',),
            },
        ),
    ]
